name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_filewatcher_service:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/FileWatcher.Service/FileWatcher.Service.csproj
      env: |
        TELERIK_USERNAME: {{ secrets.TELERIK_NUGET_SERVER_USERNAME }}
        TELERIK_PASSWORD: {{ secrets.TELERIK_NUGET_SERVER_PASSWORD }}
    
    - name: Build
      run: dotnet build src/FileWatcher.Service/FileWatcher.Service.csproj --no-restore
