name: Release - File Watcher Service

on:
  push:
    branches: [ release-file-watcher-service ]

jobs:
  build_filewatcher_service:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    
    - name: Restore dependencies
      run: dotnet restore src/FileWatcher.Service/FileWatcher.Service.csproj --configfile src/nuget.config
      env:
        TELERIK_USERNAME: ${{ secrets.TELERIK_NUGET_SERVER_USERNAME }}
        TELERIK_PASSWORD: ${{ secrets.TELERIK_NUGET_SERVER_PASSWORD }}
    
    - name: Build
      run: dotnet build src/FileWatcher.Service/FileWatcher.Service.csproj --no-restore --configuration Release

    - name: Publish
      run: dotnet publish src/FileWatcher.Service/FileWatcher.Service.csproj --configuration Release --framework net5.0-windows10.0.17763.0 --runtime win10-x86 -p:PublishSingleFile=true
 
    - uses: actions/upload-artifact@v2
      with:
        name: FileWatcherService
        path: src/FileWatcher.Service/bin/Release/net5.0-windows10.0.17763.0/win10-x86/publish
